### ISSUE TITLE
errors building niivue on Ubuntu 20.04

### ISSUE THREAD

**Issue by mrneont** [niivue/niivue#552]
Hi, All-

I have these versions of the listed dependencies nodejs and npm:
```
$nodejs -v
v10.19.0

$ npm -v
3.10.10
```

... but I get the following errors when I try to build niivue with `npm install |& tee ${logfile}.txt`:
```
...
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @esbuild/linux-arm64@0.17.14: wanted {"os":"linux","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @esbuild/freebsd-x64@0.17.14 (node_modules/esbuild/node_modules/@esbuild/freebsd-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @esbuild/freebsd-x64@0.17.14: wanted {"os":"freebsd","arch":"x64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.2 (node_modules/rollup/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN jest@29.5.0 requires a peer of node-notifier@^8.0.1 || ^9.0.0 || ^10.0.0 but none was installed.
npm WARN jest-cli@29.5.0 requires a peer of node-notifier@^8.0.1 || ^9.0.0 || ^10.0.0 but none was installed.
npm WARN vite@4.2.1 requires a peer of less@* but none was installed.
npm WARN vite@4.2.1 requires a peer of sass@* but none was installed.
npm WARN vite@4.2.1 requires a peer of stylus@* but none was installed.
npm WARN vite@4.2.1 requires a peer of sugarss@* but none was installed.
npm WARN vite@4.2.1 requires a peer of terser@^5.4.0 but none was installed.
npm WARN @jest/core@29.5.0 requires a peer of node-notifier@^8.0.1 || ^9.0.0 || ^10.0.0 but none was installed.
npm WARN jest-config@29.5.0 requires a peer of ts-node@>=9.0.0 but none was installed.
npm WARN @jest/reporters@29.5.0 requires a peer of node-notifier@^8.0.1 || ^9.0.0 || ^10.0.0 but none was installed.
npm WARN puppeteer-core@19.8.1 requires a peer of typescript@>= 4.7.4 but none was installed.
npm WARN @puppeteer/browsers@0.3.0 requires a peer of typescript@>= 4.7.4 but none was installed.
npm WARN ws@8.13.0 requires a peer of bufferutil@^4.0.1 but none was installed.
npm WARN ws@8.13.0 requires a peer of utf-8-validate@>=5.0.2 but none was installed.
npm WARN node-fetch@2.6.7 requires a peer of encoding@^0.1.0 but none was installed.
npm ERR! Linux 5.15.0-60-generic
npm ERR! argv "/home/ptaylor/miniconda3/envs/py37_afni_jup_sph/bin/node" "/home/ptaylor/miniconda3/envs/py37_afni_jup_sph/bin/npm" "install"
npm ERR! node v6.13.1
npm ERR! npm  v3.10.10
npm ERR! path /data/PROJECTS/niivue_code/BUILDNEW/node_modules/.staging/@types/graceful-fs-6bdfb638/package.json
npm ERR! code ENOTDIR
npm ERR! errno -20
npm ERR! syscall open

npm ERR! ENOTDIR: not a directory, open '/data/PROJECTS/niivue_code/BUILDNEW/node_modules/.staging/@types/graceful-fs-6bdfb638/package.json'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /data/PROJECTS/niivue_code/BUILDNEW/npm-debug.log

> @niivue/niivue@0.33.1 build /data/PROJECTS/niivue_code/BUILDNEW
> npx prettier --write src/ && npx vite build --emptyOutDir --base=./ && npm run copy-test && npm run copy-demo

module.js:478
    throw err;
    ^

Error: Cannot find module 'libnpx'
    at Function.Module._resolveFilename (module.js:476:15)
    at Function.Module._load (module.js:424:25)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/share/npm/bin/npx-cli.js:3:13)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)

npm ERR! Linux 5.15.0-60-generic
npm ERR! argv "/home/ptaylor/miniconda3/envs/py37_afni_jup_sph/bin/node" "/home/ptaylor/miniconda3/envs/py37_afni_jup_sph/bin/npm" "run" "build"
npm ERR! node v6.13.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! @niivue/niivue@0.33.1 build: `npx prettier --write src/ && npx vite build --emptyOutDir --base=./ && npm run copy-test && npm run copy-demo`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @niivue/niivue@0.33.1 build script 'npx prettier --write src/ && npx vite build --emptyOutDir --base=./ && npm run copy-test && npm run copy-demo'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @niivue/niivue package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npx prettier --write src/ && npx vite build --emptyOutDir --base=./ && npm run copy-test && npm run copy-demo
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @niivue/niivue
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @niivue/niivue
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /data/PROJECTS/niivue_code/BUILDNEW/npm-debug.log
** ERROR IN BUILD
   e /data/PROJECTS/niivue_code/o.build_src_2023_03_29_06_03_1680087397.txt
```

Are there other dependencies need or more particular version number requirements for existing dependencies?

**Comment by hanayik** [comment]
@mrneont, I would suggest updating the at leat the current LTS version of nodejs + npm. v10.x.x is quite old and not officially supported. I'm guessing this is due to the outdated ubuntu package versions (just a guess)?

https://nodejs.dev/en/about/releases/

can you try that and then report back? We can update the readme as well to mention this.

**Comment by neurolabusc** [comment]
@mrneont I am unable to replicate on my 20.04 system

```
$ lsb_release -a
 No LSB modules are available.
 Distributor ID:	Ubuntu
 Description:	Ubuntu 20.04.3 LTS
 Release:	20.04
 Codename:	focal
$ npm -v
 8.6.0
$ node -v
 v18.0.0
$ nodejs
 Command 'nodejs' not found, but can be installed with:
 sudo apt install nodejs
```
I am able to successfully run:

```
git clone https://github.com/niivue/niivue.git
cd niivue
npm install
npm run dev
```
I do get a warning:
```
New major version of npm available! 8.6.0 -> 9.6.2
```
But things still function. Notice that my system does not have `nodejs` installed, but I do have a fairly recent version of `node`.

**Comment by hanayik** [comment]
closing this since an upgrade to at leat the LTS version of Node should resolve it! Reopen if needed!

**Comment by mrneont** [comment]
Cool, thanks.  The issue appears to be the default version of nodejs installed by conda, which was that low.
I updated to get nodejs 18.0.0, and then I was indeed able to build.  Thanks for the solution.

I see on the main github page you have nodejs version numbers listed here:
https://github.com/niivue/niivue#supported-nodejs-versions-for-buildingdeveloping-with-niivue
... but for those who miss that part and jump to here:
https://github.com/niivue/niivue#local-development
... it might be nice to mention the minimal nodejs version number needed there, as well.
