### ISSUE TITLE
Property this.crosshairs3D is getting null when a react component re-renders

### ISSUE THREAD

**Issue by Keerthan-HS** [niivue/niivue#618]
Hi Team,

I am trying to write functionality in React that shows and hides crosshair on the button toggle. I observed that this.crosshairs3D is getting null when a component re-renders. Please find the error below:

Cannot read properties of null (reading 'mm')
TypeError: Cannot read properties of null (reading 'mm')
    at Niivue.setCrosshairWidth (http://localhost:3000/main.9b2d78795d1fe34cac08.hot-update.js:51699:51)
    at toggleCrossHair (http://localhost:3000/main.a6f6f883ab16a1791ed8.hot-update.js:59:10)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:92221:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:92265:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:92320:35)
    at invokeGuardedCallbackAndCatchFirstError (http://localhost:3000/static/js/bundle.js:92334:29)
    at executeDispatch (http://localhost:3000/static/js/bundle.js:95956:7)
    at processDispatchQueueItemsInOrder (http://localhost:3000/static/js/bundle.js:95982:11)
    at processDispatchQueue (http://localhost:3000/static/js/bundle.js:95993:9)
    at dispatchEventsForPlugins (http://localhost:3000/static/js/bundle.js:96002:7)

Please find the code below:

```
function NiivueComponent(props) {

  const canvas = useRef()

 const nv = new Niivue();
  const { imageUrl } = props
  useEffect(() => {
 
      const volumeList = [
        {
          url: imageUrl,
        },
      ];

      nv.attachToCanvas(canvas.current);

      nv.loadVolumes(volumeList);

      nv.setSliceType(nv.sliceTypeSagittal);
      nv.loadDrawingFromUrl("https://niivue.github.io/niivue/images/lesion.nii.gz"); 

  }, [imageUrl])

  const toggleCrossHair = () => {
    if (toggle) {
      nv.setCrosshairWidth(1);
    } else {
      nv.setCrosshairWidth(0);
    }
    
    setToggle(!toggle)
  }

  return (
    <React.Fragment>
      <div className="container">
        <button onClick={toggleCrossHair} className='my-2'>Toggle Cross Hair</button>
        <div className='p-2 h-100'>

          <canvas ref={canvas} height={500} />
        </div>
      </div>


    </React.Fragment>
  );

}
```

Please help me out with this issue.

Thanks in advance

**Comment by neurolabusc** [comment]
@Keerthan-HS I can not replicate this issue with [0.35.1](https://niivue.github.io/niivue/features/niivue.umd.js). Can you please update your code (you should see `NIIVUE VERSION  0.35.1` in the console).

**Comment by Keerthan-HS** [comment]
Hi @neurolabusc, it looks good after updating to 0.35.1. 

Thank you
