### ISSUE TITLE
Loading niftis that don't have a `.nii` or `.nii.gz` extension

### ISSUE THREAD

**Issue by pwighton** [niivue/niivue#812]
If a nifti file does not have a `.nii.gz` or `.nii` extension, is there a way to load it into niivue?  Nifti files on DANDI seem to be stored without file extensions.

Consider the nifti file `average_template_50.nii.gz` on [this page](https://dandiarchive.org/dandiset/000066/draft/files?location=derivatives%2Ftemplatecreator&page=1)

Copying the download link, and running `curl -I` reveals the actual url of the file as:
https://dandiarchive.s3.amazonaws.com/blobs/472/10e/47210e31-7e86-4a9d-bcad-413825c4250a

Downloading this file results in a local file called `47210e31-7e86-4a9d-bcad-413825c4250a`.  Using the [drag and drop example](https://niivue.github.io/niivue/features/draganddrop.html), dragging the file generates the following error:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'toUpperCase')
    at _Niivue.getFileExt (index.ts:1790:15)
    at _Niivue.dropListener (index.ts:1943:30)
```

However if I rename the file to `47210e31-7e86-4a9d-bcad-413825c4250a.nii.gz` the drag and drop example works.

A similar issue occurs trying to load from the URL directly.  Using a modified version of the 'basic multiplanar' example:
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width,initial-scale=1.0" />
    <title>Basic Multiplanar</title>
    <link rel="stylesheet" href="https://niivue.github.io/niivue/features/light.css" />
  </head>
  <body>
    <noscript>
      <strong>niivue requires JavaScript.</strong>
    </noscript>
    <header>
      <select id="sliceType">
        <option value="0">Axial</option>
        <option value="1">Coronal</option>
        <option value="2">Sagittal</option>
        <option value="4">Render</option>
        <option value="3" selected>A+C+S+R</option>
      </select>
    </header>
    <main id="container">
      <canvas id="gl1"></canvas>
    </main>
    <footer id="intensity">&nbsp;</footer>
  </body>
</html>
<!-- <script type="module" async></script> -->
<script type="module" async>
  import * as niivue from "https://niivue.github.io/niivue/dist/index.js";

  var drop = document.getElementById("sliceType");
  drop.onchange = function () {
    let st = parseInt(document.getElementById("sliceType").value);
    nv1.setSliceType(st);
  }
  function handleIntensityChange(data) {
    document.getElementById("intensity").innerHTML =
      "&nbsp;&nbsp;" + data.string;
    console.log(data);
  }
  var volumeList1 = [
    { 
      url: "https://dandiarchive.s3.amazonaws.com/blobs/472/10e/47210e31-7e86-4a9d-bcad-413825c4250a",
      colormap: "gray",
      visible: true,
      opacity: 1
    }
  ];
  var nv1 = new niivue.Niivue({
    dragAndDropEnabled: true,
    onLocationChange: handleIntensityChange,
  });
  // nv1.setRadiologicalConvention(false);
  // nv1.opts.multiplanarForceRender = true;
  nv1.attachTo("gl1");
  nv1.loadVolumes(volumeList1);
  nv1.setSliceType(nv1.sliceTypeMultiplanar);
</script>
```

Generates the following error:
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'isMosaic')
    at daikon2.Series.buildSeries (series.js:372:36)
    at _NVImage.readDICOM (index.ts:766:17)
    at new _NVImage (index.ts:225:23)
    at _NVImage.loadFromUrl (index.ts:2780:15)
    at async _Niivue.addVolumeFromUrl (index.ts:1803:20)
    at async _Niivue.loadVolumes (index.ts:3668:7)
```

Is there some parameter I can pass to `loadVolumes()` to force niivue to treat the file as nifti?

**Comment by hanayik** [comment]
@pwighton , you can set the name value explicitly to control this. You can modify your code above to be this:

```
var volumeList1 = [
    { 
      url: "https://dandiarchive.s3.amazonaws.com/blobs/472/10e/47210e31-7e86-4a9d-bcad-413825c4250a",
      name: "anyThingYouWant.nii.gz" // or .nii, but we infer decompressing from the .gz
      colormap: "gray",
      visible: true,
      opacity: 1
    }
  ];
```

**Comment by pwighton** [comment]
Perfect. Thanks @hanayik! 

Closing the issue as solved.
